// <auto-generated />
using System;
using Metrobus.Services.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Metrobus.Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210203024622_metrobusmigration")]
    partial class metrobusmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Metrobus.Services.Models.Alcaldias", b =>
                {
                    b.Property<int>("AlcaldiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlcaldiaID");

                    b.ToTable("Alcaldias");
                });

            modelBuilder.Entity("Metrobus.Services.Models.Metrobuses", b =>
                {
                    b.Property<int>("MetrobusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vehicle_ID")
                        .HasColumnType("int");

                    b.HasKey("MetrobusID");

                    b.ToTable("Metrobuses");
                });
#pragma warning restore 612, 618
        }
    }
}
